name: Convert Markdown to HTML

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create coverage directory
      run: mkdir -p coverage

    - name: Samip Regmi
      uses: jaywcjlove/markdown-to-html-cli@main
      with:
        source: README.md
        output: coverage/action.html
        github-corners: https://github.com/samTime101/
        favicon: https://media.licdn.com/dms/image/D4D03AQGG7Of9-lWWlQ/profile-displayphoto-shrink_200_200/0/1716030089681?e=2147483647&v=beta&t=8T8ApCZJnu71wgTVGYBeiQ1LEVm6BTsoJ07pTmILO6k

    - name: Upload HTML artifact
      uses: actions/upload-artifact@v3
      with:
        name: html-file
        path: coverage/action.html
